---
version: 0
os: linux
files:
  - source: /
    destination: /app
hooks:
  BeforeInstall:
    - location: ./before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./start_server.sh
      timeout: 300
      runas: root
